version: '3.9'

services:
  helix:
    container_name: helix-alpha
    image: registry.helix-dev.synadia.io/helix:tag-rc
    hostname: helix
    command: ["-c", "/conf/helix/rna.cue", "server", "start"]
    volumes:
      - conf:/conf
      - helix-data:/app/data
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - prometheus
      - nats-a
      - nats-b
      - nats-c

  postgres:
    container_name: helix-alpha-postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: helix
      POSTGRES_PASSWORD: helix
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    container_name: helix-alpha-prometheus
    image: prom/prometheus
    volumes:
      - prom-data:/prometheus


  nats-bootstrap:
    container_name: nats-bootstrap
    image: natsio/nats-box:latest
    entrypoint: ["sh"]
    command: ["/setup/bootstrap.sh", "-s"]
    volumes:
      - conf:/conf
      - ./bootstrap.sh:/setup/bootstrap.sh:ro
      - ./helix.json:/setup/helix.json:ro

  nats-a:
    container_name: helix-alpha-nats-a
    image: nats:2.9.9-alpine
    hostname: nats
    command: ["nats-server", "--config", "/conf/helix/nats-a/nats-server.conf"]
    volumes:
      - conf:/conf
      - nats-a:/data
    ports:
      - 4222:4222
    depends_on:
      nats-bootstrap:
        condition: service_completed_successfully

  nats-b:
    container_name: helix-alpha-nats-b
    image: nats:2.9.9-alpine
    hostname: nats
    command: ["nats-server", "--config", "/conf/helix/nats-b/nats-server.conf"]
    volumes:
      - conf:/conf
      - nats-b:/data
    ports:
      - 4223:4222
    depends_on:
      nats-bootstrap:
        condition: service_completed_successfully

  nats-c:
    container_name: helix-alpha-nats-c
    image: nats:2.9.9-alpine
    hostname: nats
    command: ["nats-server", "--config", "/conf/helix/nats-c/nats-server.conf"]
    volumes:
      - conf:/conf
      - nats-c:/data
    ports:
      - 4224:4222
    depends_on:
      nats-bootstrap:
        condition: service_completed_successfully

volumes:
  conf: {}
  nats-a: {}
  nats-b: {}
  nats-c: {}
  helix-data: {}
  postgres-data: {}
  prom-data: {}
